### ISSUE TITLE
Think about data races

### ISSUE THREAD

**Issue by DrJoLe** [JamFactoryApp/jamfactory-backend#10]
Currently solved using sync.Mutex.

Other possibilities are sync/atomic and channels.

Performancewise sync.Mutex should be better for a small number of concurrent goroutines, channels should be better for a large number of goroutines.

sync.Mutex is easier to read inmy opinion. I think channels would require a more thorough consideration on where and how to use them correctly.

**Comment by exp625** [comment]
Fixed by the big R
