### ISSUE TITLE
Switch from Socket.IO to native Websockets

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-backend#13]

**Comment by exp625** [comment]
Most popular package in go would be: https://github.com/gorilla/websocket

**Comment by DrJoLe** [comment]
https://github.com/gorilla/websocket actually looks pretty simple to implement. Would like to tackle

**Comment by exp625** [comment]
Would also like to tackle. Creating a WebSocket is not the problem. However, we should discuss how we can implement the same functionality as Socket.IO.

**Comment by DrJoLe** [comment]
#32
