### ISSUE TITLE
Docker-compose file for production does not specify a path to build against.

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-backend#26]
When selecting the docker-compose-prod.yml file using the -f flag, docker-compose fails with the error message
``TypeError: You must specify a directory to build in path``

Suggestes fix:

Change: ``build: .\Dockerfile-prod`` to

```
build:
  context: .
  dockerfile: ,\Dockerfile-prod
```

**Comment by DrJoLe** [comment]
i know i know. I'm on it
