### ISSUE TITLE
Prevent a Host to Join an other JamSession as a Guest

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-backend#76]
The Host can currently join his own JamSession as a Guest

**Comment by DrJoLe** [comment]
How?

**Comment by exp625** [comment]
Create a JamSession as a Host -> Go to Debug -> Join with the JamLabel -> Host joined as a Guest

**Comment by exp625** [comment]
We keep track of the users joined JamSession in the session. Maybe check the session if a join request is allowed or the user needs to leave his own JamSession first. Would need a check if the JamSession saved in the session was deleted by Housekeeping.

**Comment by DrJoLe** [comment]
Makes sense. Did we not have a "user already joined a JamSession" message once? Maybe it got lost under the big R...

**Comment by exp625** [comment]
We had. Now its gone :(

**Comment by exp625** [comment]
#BigR

**Comment by DrJoLe** [comment]
Too bad. Btw. I like #R with the implicit "big" better 😂

**Comment by exp625** [comment]
I propose #𝓡
