### ISSUE TITLE
Make error messages consistent.

### ISSUE THREAD

**Issue by DrJoLe** [JamFactoryApp/jamfactory-backend#8]

**Comment by DrJoLe** [comment]
https://github.com/gorilla/handlers
https://godoc.org/github.com/gorilla/handlers#LoggingHandler

**Comment by DrJoLe** [comment]
https://godoc.org/github.com/gorilla/handlers#CombinedLoggingHandler

**Comment by DrJoLe** [comment]
#18

**Comment by DrJoLe** [comment]
[log.txt](https://github.com/JamFactoryApp/jamfactory-backend/files/5343973/log.txt)

**Comment by exp625** [comment]
Not an issue anymore
